SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 1

SHOT_RADIUS = 5

CARD_HEIGHT = 50
CARD_FONT_SIZE = 24
CARD_PADDING = 10

FIRERATE_BASE_LEVEL = 1
MULTI_SHOT_BASE_LEVEL = 1
FIRERATE_COST = 10
MULTI_SHOT_COST = 20
MAX_FIRERATE_LEVEL = 10
MAX_MULTI_SHOT_LEVEL = 10
